//defines.h
#define SETBIT(WORD,BITPOS) (WORD |=(u32)1<<BITPOS) //SETBIT 
#define CLRBIT(WORD,BITPOS) (WORD&=(~((u32)1<<BITPOS)))  ///CLEAR BIT 
#define CPLBIT(WORD,BITPOS) (WORD^=(u32)1<<BITPOS) ////COMPLIMENT BIT 
#define READBIT(WORD,BITPOS) ((WORD >> BITPOS)&1)
#define WRITEBIT(WORD,BITPOS,BITLEVEL) WORD=((WORD&~(1<<BITPOS)) |(BITLEVEL << BITPOS))
//#define READWRITEBIT(WORD,DBIT,SBIT) WORD=((WORD&~((u32)1<<DBIT))|(SBIT<<DBIT))
#define READWRITEBIT(WORD,DBIT,SBIT) \
WORD=((WORD&~((u32)1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))
#define READNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLEVAL) WORD=((WORD&~(15<< STARTBITPOS))|(NIBBLEVAL << STARTBITPOS))
#define READBYTE(WORD,STARTBITPOS) ((WORD>> STARTBITPOS)&255)
#define WRITEBYTE(WORD,STARTBITPOS,BYTEVAL) WORD=((WORD&~(255<<STARTBITPOS))|(BYTEVAL<<STARTBITPOS))
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~((u32)1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))


